### ISSUE TITLE
[help wanted]

### ISSUE THREAD

**Issue by nicklonergan** [NARCOTIC/Instagram-Bulk-Delete#1]
Hi I found your extension upon searching for a solution for my instagram account and looks like the recent updates to instagram layout has caused your extension to be unusable. Could you please provide a fix/update or perhaps some guidance to make the extension usable?
Regards

**Comment by NARCOTIC** [comment]
Couldn't find the issue. Please download the repository again and try again.

**Comment by nicklonergan** [comment]
Hi, I've managed to get the extension to run, but it appears the "deleted posts" counter is lagged somehow, plus I've tried your extension to run and delete 2000+ post, maximum posts being able to delete per run is around 24-36 depends on luck, once IG's bot detected automation it will just show up a blank page, have to reload page and rerun the extension again. I just think if it's possible to add delays and random time for the next delete post action then perhaps you'll manage to delete more post per run. From my own experience you can delete 24 post per run, and repeat for around 10-15 runs, after this the delete function on web browser will be disabled til the next day. Despite those little things, your extension is the closest things to what I found and have been helpful, I've grinded it out and manage to clean up 2000+ posts using your extension within a week, thanks for your creation. What I've listed  above may improve the experience using the extension but may not needed, at the moment can confirm the tool works, just limited.

**Comment by Kancha0** [comment]
sir you have any video
