### ISSUE TITLE
Discrepancy between Readme and extension description

### ISSUE THREAD

**Issue by 100DogsPerHour** [NARCOTIC/Instagram-Bulk-Delete#5]
The readme says that the code simply "multiple instagram pictures at once" but the extension description says that it deletes "all photos at once" so which one is it? Can we not choose which photos to delete? I would highly recommend allowing us to choose which ones please.

**Comment by NARCOTIC** [comment]
The program runs through all the pictures and deletes them one by one. You can stop the program at any point to stop deleting photos. This tool is created for users who wants to delete all the pictures from their Instagram page. Thanks for the suggestion though. Will try to add that feature.
