### ISSUE TITLE
Throwing error on .click() in content.js

### ISSUE THREAD

**Issue by trenigma** [NARCOTIC/Instagram-Bulk-Delete#8]
Hi all, 

While running the extension in Chrome, I'm getting the following errors in the console:

https://github.com/NARCOTIC/Instagram-Bulk-Delete/blob/85cfcd5ee9b697c3f37ca9cd6eee189744c9e036/content.js#L16
`Uncaught TypeError: Cannot read properties of null (reading 'click')
    at content.js:16:56
(anonymous) @ content.js:16
setTimeout (async)
prepare @ content.js:15
(anonymous) @ content.js:43
`

and 

https://github.com/NARCOTIC/Instagram-Bulk-Delete/blob/85cfcd5ee9b697c3f37ca9cd6eee189744c9e036/content.js#L27

`content.js:27 Uncaught TypeError: Cannot read properties of null (reading 'click')
    at content.js:27:63
(anonymous) @ content.js:27
setTimeout (async)
bulkDelete @ content.js:26
(anonymous) @ content.js:44`

Please advise.. thanks!

**Comment by NARCOTIC** [comment]
Some changes on Instagram profile page is causing this issue: `Uncaught TypeError: Cannot read properties of null (reading 'click')`. Issue has been partially fixed. Code works with errors. BE ADVISED: At some point Instagram will detect the automated activity and prevent you from deleting posts. Then wait about 5-10 minutes and try again.
